// Generates `src/index.ts` from the JSON Schemas in ../../schemas/v1.
// Resolves cross-file $refs by bundling each top-level schema first,
// then runs json-schema-to-typescript over the bundled tree.

import { compile } from "json-schema-to-typescript";
import $RefParser from "@apidevtools/json-schema-ref-parser";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SCHEMAS = resolve(ROOT, "../../schemas/v1");

const TARGETS = [
  { file: `${SCHEMAS}/domain.schema.json`, title: "Domain" },
  { file: `${SCHEMAS}/ws/server.schema.json`, title: "ServerMessage" },
  { file: `${SCHEMAS}/ws/client.schema.json`, title: "ClientMessage" },
];

const COMPILE_OPTS = {
  bannerComment: "",
  additionalProperties: false,
  strictIndexSignatures: true,
  style: { singleQuote: false, semi: true },
  unreachableDefinitions: true, // emit every $def, even if not transitively used
};

const banner = `/**
 * AUTO-GENERATED by packages/ts/scripts/gen.mjs from schemas/v1/**.
 * Do not edit by hand. Run \`make gen-ts\` (or \`npm run gen\`) to regenerate.
 */
/* eslint-disable */
`;

async function main() {
  const out = [banner];

  for (const { file, title } of TARGETS) {
    const bundled = await $RefParser.bundle(file);
    // Force a stable top-level title so the generated TS has predictable names.
    bundled.title ??= title;
    const ts = await compile(bundled, title, COMPILE_OPTS);
    out.push(`// ----- generated from ${file.replace(SCHEMAS, "schemas/v1")} -----\n`);
    out.push(ts);
  }

  // Convenience re-exports for common names.
  out.push(`
// ----- convenience type aliases -----

/** Server -> client tagged union, equivalent to ServerMessage. */
export type WsMessage = ServerMessage;

/** Convenience: the union of all server-emitted message \`type\` discriminator literals. */
export type WsMessageType = WsMessage["type"];

/** Convenience: the union of all client-emitted message \`type\` discriminator literals. */
export type ClientMessageType = ClientMessage["type"];
`);

  const target = resolve(ROOT, "src/index.ts");
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, out.join("\n"), "utf8");
  console.log(`wrote ${target}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
