// Build script: reads the JSON Schemas under ../../schemas/v1, bundles them
// into a single root document with merged `definitions`, and uses `typify`
// to generate `src/generated.rs` (included via `include!`).
//
// Cross-file `$ref`s of the form "../domain.schema.json#/$defs/X" are
// rewritten to "#/$defs/X" before bundling. `$defs` keys are renamed to
// `definitions` because schemars 0.8 (typify's parser) uses draft-07 naming.

use serde_json::{json, Map, Value};
use std::{env, fs, path::PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // Try bundled schemas first (registry install), then workspace fallback (local dev).
    let schemas_local = manifest_dir.join("schemas/v1");
    let schemas_workspace = manifest_dir.join("../../schemas/v1");
    let schemas = if schemas_local.exists() {
        schemas_local
    } else if schemas_workspace.exists() {
        schemas_workspace
    } else {
        panic!(
            "schemas not found — expected at schemas/v1/ (bundled) or ../../schemas/v1/ (workspace)"
        );
    };

    println!("cargo:rerun-if-changed={}", schemas.display());

    let domain = read(&schemas.join("domain.schema.json"));
    let server = read(&schemas.join("ws/server.schema.json"));
    let client = read(&schemas.join("ws/client.schema.json"));

    let mut defs: Map<String, Value> = Map::new();
    merge_defs(&mut defs, &domain);
    merge_defs(&mut defs, &server);
    merge_defs(&mut defs, &client);

    // Top-level `oneOf` from server + client become named definitions.
    if let Some(one) = server.get("oneOf").cloned() {
        let mut wrapper = Map::new();
        wrapper.insert("oneOf".into(), one);
        defs.insert("ServerMessage".into(), Value::Object(wrapper));
    }
    if let Some(one) = client.get("oneOf").cloned() {
        let mut wrapper = Map::new();
        wrapper.insert("oneOf".into(), one);
        defs.insert("ClientMessage".into(), Value::Object(wrapper));
    }

    // Rewrite every cross-file ref to a local one.
    rewrite_refs(&mut defs);

    let root = json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "QuaContracts",
        "type": "object",
        "definitions": Value::Object(defs),
    });

    let root_schema: schemars::schema::RootSchema =
        serde_json::from_value(root).expect("failed to parse bundled root schema");

    let mut type_space = typify::TypeSpace::new(
        typify::TypeSpaceSettings::default()
            .with_struct_builder(true)
            .with_derive("PartialEq".to_string()),
    );

    type_space
        .add_ref_types(root_schema.definitions)
        .expect("typify failed to add definitions");

    let stream = type_space.to_stream();
    let parsed = syn::parse2::<syn::File>(stream).expect("typify produced invalid Rust");
    let pretty = prettyplease::unparse(&parsed);

    let out = out_dir.join("generated.rs");
    let banner = "// AUTO-GENERATED by build.rs from schemas/v1/**.\n\
                  // Do not edit by hand. Regenerated on every `cargo build`.\n\n";
    fs::write(&out, format!("{banner}{pretty}")).expect("write generated.rs");

    // Copy schemas to OUT_DIR so lib.rs can embed them via include_str!.
    for (src, dst) in [
        (schemas.join("ws/server.schema.json"), out_dir.join("server.schema.json")),
        (schemas.join("ws/client.schema.json"), out_dir.join("client.schema.json")),
        (schemas.join("domain.schema.json"),    out_dir.join("domain.schema.json")),
    ] {
        fs::copy(&src, &dst)
            .unwrap_or_else(|e| panic!("copy {} -> {}: {e}", src.display(), dst.display()));
    }

    println!("cargo:warning=qua-media-contracts: wrote {}", out.display());
}

fn read(path: &std::path::Path) -> Value {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("parse {}: {e}", path.display()))
}

fn merge_defs(into: &mut Map<String, Value>, schema: &Value) {
    if let Some(Value::Object(d)) = schema.get("$defs") {
        for (k, v) in d {
            if into.contains_key(k) {
                panic!("duplicate $defs entry: {k}");
            }
            into.insert(k.clone(), v.clone());
        }
    }
}

/// Recursively rewrite `"../domain.schema.json#/$defs/X"` -> `"#/definitions/X"`
/// and `"#/$defs/X"` -> `"#/definitions/X"`.
fn rewrite_refs(defs: &mut Map<String, Value>) {
    for v in defs.values_mut() {
        rewrite(v);
    }
}

fn rewrite(value: &mut Value) {
    match value {
        Value::Object(map) => {
            if let Some(Value::String(r)) = map.get_mut("$ref") {
                if let Some(idx) = r.find("#/$defs/") {
                    let name = &r[idx + "#/$defs/".len()..];
                    *r = format!("#/definitions/{name}");
                }
            }
            for (_, child) in map.iter_mut() {
                rewrite(child);
            }
        }
        Value::Array(arr) => {
            for child in arr {
                rewrite(child);
            }
        }
        _ => {}
    }
}
